const fs=require('fs'),assert=require('assert');
const read=f=>fs.readFileSync(f,'utf8'); const s=read('script.js'),a=read('admin.js'),h=read('index.html'),ah=read('admin.html'),sql=read('supabase_patch_stop_lagman_fish.sql');
const tests=[]; const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t('120g removed',()=>{assert(!s.includes('potato-balls-120'));assert(s.includes('potato-balls-200'))});
t('7 lagman',()=>{for(const id of ['lagman-guyru','lagman-suyru','lagman-guyru-tsomyan','lagman-suyru-tsomyan','lagman-moguru','lagman-moshuru','lagman-hauhau'])assert(s.includes(id)&&sql.includes(id))});
t('fish variants',()=>{for(const id of ['fish-sudak','fish-sazan','fish-assorti'])assert(s.includes(id)&&sql.includes(id));for(const v of ['500g','700g','1kg','1.5kg'])assert(s.includes(v))});
t('same fish photo',()=>assert((s.match(/assets\/menu\/fish-assorti\.webp/g)||[]).length>=3));
t('phone tel',()=>assert(h.includes('tel:+77781577796')&&h.includes('+7 (778) 157-77-96')));
t('Kaspi Red label',()=>assert(h.includes('Kaspi Red')));
t('nav new categories',()=>{for(const x of ['Восточка','Рыба','Напитки'])assert(s.includes(x))});
t('prep 60/90',()=>assert(ah.includes('60 минут')&&ah.includes('90 минут')&&a.includes('[20,30,40,60,90]')));
t('client prep server status',()=>assert(s.includes('status.prep_minutes')));
t('set modal',()=>assert(h.includes('set-modal')&&s.includes('openSetModal')&&s.includes('addSetFromModal')));
t('stop UI',()=>assert(s.includes('stop-badge')&&s.includes('loadAvailability')&&ah.includes('STOP-лист')));
t('stop server',()=>assert(sql.includes('product_availability')&&sql.includes('set_product_stop_v1')&&sql.includes('is_stopped')));
t('server canonical prices',()=>assert(sql.includes("v_price := 1600")&&sql.includes("v_price := 8800")));
t('existing drinks/sauces preserved',()=>assert(s.includes('sauce-ketchup')&&s.includes('cola-2')&&s.includes('sushi-philadelphia')));
t('assets exist',()=>{for(const f of ['assets/menu/strips.webp','assets/menu/ayran.webp','assets/menu/fish-assorti.webp','assets/menu/guyru-lagman.webp'])assert(fs.existsSync(f),f)});
const failed=tests.filter(x=>!x[1]); console.log(JSON.stringify({passed:tests.length-failed.length,failed:failed.length,results:tests},null,2)); if(failed.length)process.exit(1);
